services:
  - type: web
    name: student-crud-api 202326900094
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /docs
